export type PricingTrialReleaseBucket = 'allowed_quoted_in_trial' | 'estimated_only_in_trial' | 'handoff_only_in_trial'

export type PricingTrialReleaseScopeType = 'item' | 'bundle'

export type PricingTrialReleaseEntry = {
  id: string
  scopeType: PricingTrialReleaseScopeType
  bucket: PricingTrialReleaseBucket
  label: string
  runtimeExpectation: 'quoted' | 'estimated' | 'handoff_required'
  acceptanceGateIds: string[]
  notes: string
  representativeMessage: string
}

export const PRICING_TRIAL_SCOPE_CANONICAL_DOC_PATH = 'docs/pricing-trial-scope.md'

export const PRICING_TRIAL_SCOPE_SUPERSEDED_RELEASE_DOCS = [
  'docs/workbook-pricing-acceptance-gate.md',
  'docs/workbook-order-alignment-review.md',
  'docs/workbook-bundle-main-box-path-review.md',
  'docs/pricing-module-maturity-review.md',
] as const

export const PRICING_TRIAL_RELEASE_ENTRIES: PricingTrialReleaseEntry[] = [
  {
    id: 'tuck_end_standard',
    scopeType: 'item',
    bucket: 'allowed_quoted_in_trial',
    label: '标准 tuck_end_box',
    runtimeExpectation: 'quoted',
    acceptanceGateIds: ['tuck_end_main_item_quoted'],
    notes: '标准双插盒主件是当前 limited trial 的 quoted 基线。',
    representativeMessage: '双插盒：7*5*5CM，展开26*16CM，350克白卡，正反四色 + 啤 + 粘合，5000',
  },
  {
    id: 'mailer_validated',
    scopeType: 'item',
    bucket: 'allowed_quoted_in_trial',
    label: '已验证 mailer_box',
    runtimeExpectation: 'quoted',
    acceptanceGateIds: ['mailer_box_quoted_paths'],
    notes: '已验证飞机盒标准路径允许自动正式报价。',
    representativeMessage: '飞机盒：20*12*6CM，300克白卡，四色印刷，5000个',
  },
  {
    id: 'window_gloss_film',
    scopeType: 'item',
    bucket: 'allowed_quoted_in_trial',
    label: 'window_box 标准 gloss-film 路径',
    runtimeExpectation: 'quoted',
    acceptanceGateIds: ['window_box_gloss_quoted'],
    notes: '只限标准覆光胶 + 胶片 line-item 完整路径。',
    representativeMessage: '开窗彩盒，21*17*31cm，400克单铜+印四色+表面过光+裱+开窗贴0.2厚胶片23.5*14CM+啤+粘，500',
  },
  {
    id: 'window_no_film_gloss',
    scopeType: 'item',
    bucket: 'allowed_quoted_in_trial',
    label: 'window_box 标准 no-film gloss 路径',
    runtimeExpectation: 'quoted',
    acceptanceGateIds: ['window_box_no_film_gloss_quoted_candidate'],
    notes: '只限明确不贴胶片、标准覆光胶、标准材质印刷、无复杂工艺叠加的最小 no-film 单品子集。',
    representativeMessage: '双插开窗盒：110x120x95mm，300克白卡，印黑色，过光胶，开窗不贴胶片，啤成品+粘盒，2000',
  },
  {
    id: 'leaflet_standard',
    scopeType: 'item',
    bucket: 'allowed_quoted_in_trial',
    label: '标准 leaflet_insert',
    runtimeExpectation: 'quoted',
    acceptanceGateIds: ['leaflet_standard_quoted'],
    notes: '只限标准说明书，不含 generic print proxy 路径。',
    representativeMessage: '说明书：20*5CM，80克双铜纸 + 双面四色印 + 折3折，5000',
  },
  {
    id: 'leaflet_generic_high_frequency',
    scopeType: 'item',
    bucket: 'allowed_quoted_in_trial',
    label: 'generic leaflet（高频标准化）',
    runtimeExpectation: 'quoted',
    acceptanceGateIds: ['leaflet_generic_high_frequency_quoted'],
    notes: '高频 generic 说明书已进入标准化 quoted candidate，但不外推到复杂 leaflet 长尾。',
    representativeMessage: '说明书：220x170mm，80g双胶纸，单面印，6100',
  },
  {
    id: 'box_insert_standard',
    scopeType: 'item',
    bucket: 'allowed_quoted_in_trial',
    label: '标准 box_insert（显式克重）',
    runtimeExpectation: 'quoted',
    acceptanceGateIds: ['box_insert_standard_quoted_candidate'],
    notes: '只限显式克重的标准纸内托单品，不含默认克重 proxy，也不代表主盒 + 内托 bundle 已放开。',
    representativeMessage: '纸内托：20*12CM，500克白卡 + 3个专色 + 覆哑膜 + 裱 + 啤，5000',
  },
  {
    id: 'box_insert_proxy_high_frequency',
    scopeType: 'item',
    bucket: 'allowed_quoted_in_trial',
    label: 'proxy box_insert（高频标准化）',
    runtimeExpectation: 'quoted',
    acceptanceGateIds: ['box_insert_proxy_high_frequency_quoted'],
    notes: '高频默认克重 proxy 内托已进入标准化 quoted candidate，但不外推到更宽的内托长尾。',
    representativeMessage: '内托：20*12CM左右，WEB特种纸板，5000',
  },
  {
    id: 'seal_sticker_standard',
    scopeType: 'item',
    bucket: 'allowed_quoted_in_trial',
    label: '标准 seal_sticker',
    runtimeExpectation: 'quoted',
    acceptanceGateIds: ['seal_sticker_standard_quoted'],
    notes: '只限标准透明封口贴 quoted 路径。',
    representativeMessage: '透明贴纸：2.4*3CM 封口贴，透明贴纸 + 模切，5000',
  },
  {
    id: 'foil_bag_blank',
    scopeType: 'item',
    bucket: 'allowed_quoted_in_trial',
    label: 'blank foil_bag',
    runtimeExpectation: 'quoted',
    acceptanceGateIds: ['foil_bag_blank_quoted'],
    notes: '当前只放开空白铝箔袋。',
    representativeMessage: '铝铂袋：12.5*12.5CM，8丝空白铝铂袋，10000个',
  },
  {
    id: 'foil_bag_standard_printed',
    scopeType: 'item',
    bucket: 'allowed_quoted_in_trial',
    label: 'standard printed foil_bag',
    runtimeExpectation: 'quoted',
    acceptanceGateIds: ['foil_bag_standard_printed_quoted_candidate'],
    notes: '这轮只放开标准 8 丝单面四色铝箔袋单品，不外推到 generic print、双面印刷、打样或 bundle。',
    representativeMessage: '铝箔袋：12.5*12.5CM，8丝铝箔袋，单面四色印刷，10000个',
  },
  {
    id: 'carton_packaging_simple',
    scopeType: 'item',
    bucket: 'allowed_quoted_in_trial',
    label: 'simple carton_packaging',
    runtimeExpectation: 'quoted',
    acceptanceGateIds: ['carton_packaging_quoted'],
    notes: '只限 simple outer-carton / 纸箱+包装费路径。',
    representativeMessage: '纸箱+包装费：42*42*35CM，10000套',
  },
  {
    id: 'carton_packaging_standard_printed',
    scopeType: 'item',
    bucket: 'allowed_quoted_in_trial',
    label: 'standard printed carton_packaging',
    runtimeExpectation: 'quoted',
    acceptanceGateIds: ['carton_packaging_standard_printed_quoted_candidate'],
    notes: '这轮只放开标准 K636K 单面四色大外箱单品，不外推到双面印刷、成箱/包装费、打样或复杂外箱结构。',
    representativeMessage: '大外箱：42*42*35CM，K636K空白箱，单面四色印刷，啤，10000个',
  },
  {
    id: 'bundle_tuck_end_plus_leaflet',
    scopeType: 'bundle',
    bucket: 'allowed_quoted_in_trial',
    label: '标准主盒 + 标准说明书',
    runtimeExpectation: 'quoted',
    acceptanceGateIds: ['standard_bundle_quoted'],
    notes: '当前已 accepted 的标准 quoted bundle 之一。',
    representativeMessage: '双插盒：7*5*5CM，350克白卡+正反四色+专印+正面过哑胶+啤+粘合，5000；说明书：20*5CM，80克双铜纸+双面四色印+折3折，5000',
  },
  {
    id: 'bundle_tuck_end_plus_generic_leaflet',
    scopeType: 'bundle',
    bucket: 'estimated_only_in_trial',
    label: '标准双插盒 + 高频 generic 说明书',
    runtimeExpectation: 'estimated',
    acceptanceGateIds: ['single_generic_leaflet_bundle_estimated_only'],
    notes: 'generic leaflet 单品虽保留高频标准化 quoted，但挂到主盒后仍按保守 estimated 管理，避免上下文复用把组合误放大成正式报价。',
    representativeMessage: '双插盒：7*5*5CM，350克白卡+正反四色+专印+正面过哑胶+啤+粘合，5000；说明书：220x170mm，80g双胶纸，单面印，5000',
  },
  {
    id: 'bundle_tuck_end_plus_standard_insert',
    scopeType: 'bundle',
    bucket: 'allowed_quoted_in_trial',
    label: '标准双插盒 + 标准内托',
    runtimeExpectation: 'quoted',
    acceptanceGateIds: ['standard_bundle_quoted'],
    notes: '当前只放开标准双插盒 + 标准内托这一个 insert quoted bundle；不外推到其他主盒或 proxy 内托。',
    representativeMessage: '双插盒：7*5*5CM，350克白卡+正反四色+专印+正面过哑胶+啤+粘合，5000；纸内托：20*12CM，500克白卡 + 3个专色 + 覆哑膜 + 裱 + 啤，5000',
  },
  {
    id: 'bundle_mailer_plus_standard_insert',
    scopeType: 'bundle',
    bucket: 'allowed_quoted_in_trial',
    label: '已验证飞机盒 + 标准内托',
    runtimeExpectation: 'quoted',
    acceptanceGateIds: ['extended_main_plus_insert_quoted_candidate'],
    notes: '这轮 coverage 扩张第一步只把已验证 mailer_box + 标准内托纳入 extended_main_plus_insert_quoted_candidate；不外推到 window_box 或其他主盒。',
    representativeMessage: '飞机盒：20*12*6CM，300克白卡，四色印刷，5000个；纸内托：20*12CM，500克白卡 + 3个专色 + 覆哑膜 + 裱 + 啤，5000',
  },
  {
    id: 'bundle_tuck_end_plus_proxy_insert',
    scopeType: 'bundle',
    bucket: 'allowed_quoted_in_trial',
    label: '标准双插盒 + 高频 proxy 内托',
    runtimeExpectation: 'quoted',
    acceptanceGateIds: ['standard_bundle_quoted'],
    notes: '第三大步只放开标准双插盒 + 高频默认克重 proxy 内托这一条窄白名单，不外推到其他主盒 + 内托组合。',
    representativeMessage: '双插盒：7*5*5CM，350克白卡+正反四色+专印+正面过哑胶+啤+粘合，5000；内托：20*12CM左右，WEB特种纸板，5000',
  },
  {
    id: 'bundle_mailer_plus_proxy_insert',
    scopeType: 'bundle',
    bucket: 'allowed_quoted_in_trial',
    label: '已验证飞机盒 + 高频 proxy 内托',
    runtimeExpectation: 'quoted',
    acceptanceGateIds: ['extended_main_plus_insert_quoted_candidate'],
    notes: '这轮 coverage 扩张第一步只把已验证 mailer_box + 高频 proxy 内托纳入 extended_main_plus_insert_quoted_candidate；不外推到 window_box 或其他主盒。',
    representativeMessage: '飞机盒：20*12*6CM，300克白卡，四色印刷，5000个；内托：20*12CM左右，WEB特种纸板，5000',
  },
  {
    id: 'bundle_tuck_end_plus_leaflet_sticker',
    scopeType: 'bundle',
    bucket: 'allowed_quoted_in_trial',
    label: '标准主盒 / 已验证飞机盒 + 标准说明书 + 标准贴纸',
    runtimeExpectation: 'quoted',
    acceptanceGateIds: ['multi_accessory_standard_bundle_quoted_candidate'],
    notes: 'multi_accessory_standard_bundle_quoted_candidate 第一优先级：当前只放开标准双插盒 / 已验证飞机盒 + 标准说明书 + 标准贴纸，不外推到 generic leaflet、proxy insert、window_box 或更宽多配件。',
    representativeMessage: '双插盒：7*5*5CM，350克白卡+正反四色+专印+正面过哑胶+啤+粘合，5000；说明书：20*5CM，80克双铜纸+双面四色印+折3折，5000；透明贴纸：2.4*3CM 封口贴，透明贴纸 + 模切，5000',
  },
  {
    id: 'bundle_multi_accessory_standard_insert_leaflet',
    scopeType: 'bundle',
    bucket: 'allowed_quoted_in_trial',
    label: '标准主盒 / 已验证飞机盒 + 标准内托 + 标准说明书',
    runtimeExpectation: 'quoted',
    acceptanceGateIds: ['multi_accessory_standard_bundle_quoted_candidate'],
    notes: 'multi_accessory_standard_bundle_quoted_candidate 第二优先级：当前只放开标准双插盒 / 已验证飞机盒 + 标准内托 + 标准说明书，不外推到 proxy 内托或 generic leaflet。',
    representativeMessage: '双插盒：7*5*5CM，350克白卡+正反四色+专印+正面过哑胶+啤+粘合，5000；纸内托：20*12CM，500克白卡 + 3个专色 + 覆哑膜 + 裱 + 啤，5000；说明书：20*5CM，80克双铜纸+双面四色印+折3折，5000',
  },
  {
    id: 'bundle_multi_accessory_standard_insert_sticker',
    scopeType: 'bundle',
    bucket: 'allowed_quoted_in_trial',
    label: '标准主盒 / 已验证飞机盒 + 标准内托 + 标准贴纸',
    runtimeExpectation: 'quoted',
    acceptanceGateIds: ['multi_accessory_standard_bundle_quoted_candidate'],
    notes: 'multi_accessory_standard_bundle_quoted_candidate 第三优先级：当前只放开标准双插盒 / 已验证飞机盒 + 标准内托 + 标准贴纸，不外推到 proxy 内托或更宽多配件。',
    representativeMessage: '双插盒：7*5*5CM，350克白卡+正反四色+专印+正面过哑胶+啤+粘合，5000；纸内托：20*12CM，500克白卡 + 3个专色 + 覆哑膜 + 裱 + 啤，5000；透明贴纸：2.4*3CM 封口贴，透明贴纸 + 模切，5000',
  },
  {
    id: 'bundle_multi_accessory_leaflet_carton',
    scopeType: 'bundle',
    bucket: 'allowed_quoted_in_trial',
    label: '标准主盒 / 已验证飞机盒 + 标准说明书 + simple carton_packaging',
    runtimeExpectation: 'quoted',
    acceptanceGateIds: ['multi_accessory_standard_bundle_quoted_candidate'],
    notes: 'multi_accessory_standard_bundle_quoted_candidate 第四优先级：当前只放开标准双插盒 / 已验证飞机盒 + 标准说明书 + simple carton_packaging，不外推到 additional accessory 继续叠加。',
    representativeMessage: '双插盒：7*5*5CM，350克白卡+正反四色+专印+正面过哑胶+啤+粘合，5000；说明书：20*5CM，80克双铜纸+双面四色印+折3折，5000；纸箱+包装费：42*42*35CM，5000套',
  },
  {
    id: 'bundle_tuck_end_plus_sticker',
    scopeType: 'bundle',
    bucket: 'allowed_quoted_in_trial',
    label: '标准主盒 + 标准贴纸',
    runtimeExpectation: 'quoted',
    acceptanceGateIds: ['standard_bundle_quoted'],
    notes: '当前已 accepted 的标准 quoted bundle 之一。',
    representativeMessage: '双插盒：7*5*5CM，350克白卡+正反四色+专印+正面过哑胶+啤+粘合，5000；透明贴纸：2.4*3CM 封口贴，透明贴纸 + 模切，5000',
  },
  {
    id: 'bundle_blank_foil_bag_plus_carton',
    scopeType: 'bundle',
    bucket: 'allowed_quoted_in_trial',
    label: 'blank foil_bag + simple carton_packaging',
    runtimeExpectation: 'quoted',
    acceptanceGateIds: ['order_addon_bundle_quoted'],
    notes: '这是当前唯一已放开的 carton add-on quoted bundle。',
    representativeMessage: '铝铂袋：12.5*12.5CM，8丝空白铝铂袋，10000个；纸箱+包装费：42*42*35CM，10000套',
  },
  {
    id: 'bundle_main_box_plus_simple_carton',
    scopeType: 'bundle',
    bucket: 'allowed_quoted_in_trial',
    label: '标准主盒 + simple carton_packaging',
    runtimeExpectation: 'quoted',
    acceptanceGateIds: ['standard_bundle_quoted'],
    notes: '首批 coverage blocker 先只放开 allowed_quoted 主盒 + simple carton 的标准 bundle。',
    representativeMessage: '双插盒：7*5*5CM，350克白卡+正反四色+专印+正面过哑胶+啤+粘合，5000；纸箱+包装费：42*42*35CM，5000套',
  },
  {
    id: 'window_no_film',
    scopeType: 'item',
    bucket: 'estimated_only_in_trial',
    runtimeExpectation: 'estimated',
    label: 'window_box no-film（保守子集）',
    acceptanceGateIds: ['window_box_no_film_estimated'],
    notes: '不贴胶片路径中，非 glossy / 非标准 / 非完整的保守子集继续 estimated。',
    representativeMessage: '双插开窗盒：110x120x95mm，300克白卡，印黑色，开窗不贴胶片，啤成品+粘盒，2000',
  },
  {
    id: 'foil_bag_printed_custom',
    scopeType: 'item',
    bucket: 'estimated_only_in_trial',
    label: 'printed/custom foil_bag',
    runtimeExpectation: 'estimated',
    acceptanceGateIds: [],
    notes: '未进入标准 8 丝单面四色 quoted candidate 的 printed/custom foil bag 仍保守。',
    representativeMessage: '铝箔袋：12.5*12.5CM，8丝铝箔袋，单面印，10000个',
  },
  {
    id: 'carton_packaging_printed',
    scopeType: 'item',
    bucket: 'estimated_only_in_trial',
    label: 'printed carton_packaging',
    runtimeExpectation: 'estimated',
    acceptanceGateIds: [],
    notes: '未进入标准 K636K 单面四色大外箱 quoted candidate 的 printed carton 路径仍只允许参考报价。',
    representativeMessage: '大外箱：44*24.5*22.5CM，K636K空白箱，四色印刷，160个',
  },
  {
    id: 'bundle_non_whitelisted_main_plus_insert',
    scopeType: 'bundle',
    bucket: 'estimated_only_in_trial',
    label: '非白名单主盒 + 内托',
    runtimeExpectation: 'estimated',
    acceptanceGateIds: ['extended_main_plus_insert_estimated_only'],
    notes: '非白名单主盒 + 内托现已拆成三层：已验证飞机盒 + 标准/高频 proxy 内托进入 extended_main_plus_insert_quoted_candidate；window_box + 内托等其余保守子集继续留在 extended_main_plus_insert_estimated_only。',
    representativeMessage: '开窗彩盒，21*17*31cm，400克单铜+印四色+表面过光+裱+开窗贴0.2厚胶片23.5*14CM+啤+粘，500；纸内托：20*12CM，500克白卡 + 3个专色 + 覆哑膜 + 裱 + 啤，500',
  },
  {
    id: 'bundle_multi_accessory',
    scopeType: 'bundle',
    bucket: 'estimated_only_in_trial',
    label: '多配件标准 bundle（generic / proxy / 更宽保守子集）',
    runtimeExpectation: 'estimated',
    acceptanceGateIds: ['multi_accessory_standard_bundle_estimated_only'],
    notes: 'multi_accessory_standard_bundle_estimated_only 当前继续覆盖 generic leaflet / proxy insert 参与的多配件组合，以及标准双插盒 / 已验证飞机盒之外的更宽多配件标准 bundle。simple carton 不放开继续叠加其他配件。',
    representativeMessage: '双插盒：7*5*5CM，350克白卡，正反四色，5000个；说明书：20*5CM，80克双铜纸，双面四色印，折3折，5000；透明贴纸：2.4*3cm，透明贴纸，5000；纸箱+包装费：42*42*35CM，5000套',
  },
  {
    id: 'template_outside_scope',
    scopeType: 'item',
    bucket: 'handoff_only_in_trial',
    label: '模板外结构 / 复杂礼盒 / 复杂外箱',
    runtimeExpectation: 'handoff_required',
    acceptanceGateIds: [],
    notes: '当前活跃模板之外的结构继续人工兜底。',
    representativeMessage: '天地盖礼盒，帮我报价',
  },
  {
    id: 'file_dieline_driven',
    scopeType: 'item',
    bucket: 'handoff_only_in_trial',
    label: '设计稿 / 刀线图 / 高复杂文件型询价',
    runtimeExpectation: 'handoff_required',
    acceptanceGateIds: [],
    notes: '文件驱动案例继续 handoff。',
    representativeMessage: '双插盒，7*5*5CM，350克白卡，5000个，我有 PDF 设计稿',
  },
  {
    id: 'blocking_terms_materials',
    scopeType: 'item',
    bucket: 'handoff_only_in_trial',
    label: '高复杂术语 / 特材 / blocking workbook term',
    runtimeExpectation: 'handoff_required',
    acceptanceGateIds: [],
    notes: '明显依赖人工工艺判断的 blocking path 继续人工兜底。',
    representativeMessage: '飞机盒，20*12*6CM，300克白卡+Q9坑，四色，裱+啤，1000',
  },
  {
    id: 'box_insert_handoff_only',
    scopeType: 'item',
    bucket: 'handoff_only_in_trial',
    label: '复杂 box_insert',
    runtimeExpectation: 'handoff_required',
    acceptanceGateIds: [],
    notes: '复杂内托结构、EVA/磁吸等 blocking term 或模板外内托路径继续 handoff。',
    representativeMessage: '内托：20*12CM，EVA内托，5000',
  },
]

export function getPricingTrialReleaseEntries(bucket?: PricingTrialReleaseBucket, scopeType?: PricingTrialReleaseScopeType) {
  return PRICING_TRIAL_RELEASE_ENTRIES.filter((entry) => {
    if (bucket && entry.bucket !== bucket) {
      return false
    }

    if (scopeType && entry.scopeType !== scopeType) {
      return false
    }

    return true
  })
}