ALTER TYPE "ReflectionIssueType" ADD VALUE IF NOT EXISTS 'PACKAGING_PARAM_WRONG';
ALTER TYPE "ReflectionIssueType" ADD VALUE IF NOT EXISTS 'PACKAGING_PARAM_MISSING';
ALTER TYPE "ReflectionIssueType" ADD VALUE IF NOT EXISTS 'BUNDLE_STRUCTURE_WRONG';
ALTER TYPE "ReflectionIssueType" ADD VALUE IF NOT EXISTS 'PACKAGING_PRICE_INACCURATE';
ALTER TYPE "ReflectionIssueType" ADD VALUE IF NOT EXISTS 'PACKAGING_REVIEW_REASON_WRONG';
ALTER TYPE "ReflectionIssueType" ADD VALUE IF NOT EXISTS 'SHOULD_ESTIMATE_BUT_QUOTED';
ALTER TYPE "ReflectionIssueType" ADD VALUE IF NOT EXISTS 'SHOULD_HANDOFF_BUT_NOT';
ALTER TYPE "ReflectionIssueType" ADD VALUE IF NOT EXISTS 'SHOULD_QUOTED_BUT_ESTIMATED';