import type { TuckEndPhaseTwoManualReviewDraft } from './tuckEndBoxPhaseTwoDraft'

export const TUCK_END_PHASE_TWO_LIVE_REVIEW_BATCH_ONE_DRAFT = [
  {
    schemaVersion: 'tuck_end_phase_two_review_v1_draft',
    family: 'tuck_end_box',
    reviewScope: 'live_shadow',
    basicInfo: {
      conversationId: '2070',
      requestId: '7750',
      sampleReferenceId: null,
      rawText: '双插盒，7*5*5CM，350克白卡，正反四色，5000个',
      motherPoolSources: ['phase_one_tuck_end_box', 'second_phase_tuck_end_box', 'tuck_end_related_structure_keyword'],
      phaseOne: {
        family: 'tuck_end_box',
        type: 'tuck_end_box',
        status: 'quoted',
      },
      secondPhase: {
        family: 'tuck_end_box',
        type: 'tuck_end_box',
        status: 'quoted',
        statusReasons: ['tuck_end_box_in_scope'],
      },
      variantTags: [],
    },
    bucketAssessment: {
      bucket: 'quoted_clean_subset',
      pathId: 'standard_double_tuck_main_item',
      inBucketReasons: ['标准双插主件路径', 'phase-one 与 second-phase 主类和状态一致', '无窗口、无挂钩、无 companion insert、无高复杂工艺'],
      misbucketRisk: false,
      misbucketRiskReasons: [],
    },
    productAssessment: {
      familyMergeStable: true,
      packagingTypeStable: true,
      statusMatchesExpected: true,
      quotedMisrelease: false,
      highComplexityCorrectlyHandoff: null,
      quotedChecks: {
        packagingTypeResolved: true,
        coreMaterialRecipeComplete: true,
        keyLineItemsComputable: true,
        unresolvedTermsSafe: true,
      },
    },
    termAndCostAssessment: {
      blockingUnknownTerms: [],
      nonBlockingUnknownTerms: [],
      unknownCluster: false,
      unknownClusterTerms: [],
      manualAdjustmentPresent: false,
      manualAdjustmentTouchesCoreCost: false,
      coreManualAdjustmentLineCodes: [],
      lineItemsStable: true,
      stableLineItemCodes: ['face_paper', 'printing'],
      missingCoreLineItemCodes: ['die_mold', 'gluing'],
      priceProxySystematicDrift: null,
      priceProxyDriftDirection: 'not_enough_evidence',
      priceProxyNote: '当前只有 live 结果，没有同路径真实成交价对照，暂不能判定价格代理是否系统性失真。',
    },
    conclusion: {
      disposition: 'limited_role_candidate',
      blockReason: null,
      reviewNote: '这是当前最干净的 quoted 子路径样本，具备 limited role candidate 信号，但证据量仍不足以放权。',
    },
  },
  {
    schemaVersion: 'tuck_end_phase_two_review_v1_draft',
    family: 'tuck_end_box',
    reviewScope: 'live_shadow',
    basicInfo: {
      conversationId: '2068',
      requestId: '7744',
      sampleReferenceId: null,
      rawText: '双插盒：7*5*5CM，350克白卡，正反四色，5000',
      motherPoolSources: ['phase_one_tuck_end_box', 'second_phase_tuck_end_box', 'tuck_end_related_structure_keyword'],
      phaseOne: {
        family: 'tuck_end_box',
        type: 'tuck_end_box',
        status: 'quoted',
      },
      secondPhase: {
        family: 'tuck_end_box',
        type: 'tuck_end_box',
        status: 'quoted',
        statusReasons: ['tuck_end_box_in_scope'],
      },
      variantTags: [],
    },
    bucketAssessment: {
      bucket: 'quoted_clean_subset',
      pathId: 'standard_double_tuck_main_item',
      inBucketReasons: ['标准双插主件路径', 'quoted 状态与主类对齐', '无边界特征'],
      misbucketRisk: false,
      misbucketRiskReasons: [],
    },
    productAssessment: {
      familyMergeStable: true,
      packagingTypeStable: true,
      statusMatchesExpected: true,
      quotedMisrelease: false,
      highComplexityCorrectlyHandoff: null,
      quotedChecks: {
        packagingTypeResolved: true,
        coreMaterialRecipeComplete: true,
        keyLineItemsComputable: true,
        unresolvedTermsSafe: true,
      },
    },
    termAndCostAssessment: {
      blockingUnknownTerms: [],
      nonBlockingUnknownTerms: [],
      unknownCluster: false,
      unknownClusterTerms: [],
      manualAdjustmentPresent: false,
      manualAdjustmentTouchesCoreCost: false,
      coreManualAdjustmentLineCodes: [],
      lineItemsStable: true,
      stableLineItemCodes: ['face_paper', 'printing'],
      missingCoreLineItemCodes: ['die_mold', 'gluing'],
      priceProxySystematicDrift: null,
      priceProxyDriftDirection: 'not_enough_evidence',
      priceProxyNote: '与同路径其他 quoted 样本一致，当前更像稳定 clean path 复现，而不是价格代理证据。',
    },
    conclusion: {
      disposition: 'limited_role_candidate',
      blockReason: null,
      reviewNote: '重复 clean path 命中，支持标准双插主件是当前最接近 limited role 的路径。',
    },
  },
  {
    schemaVersion: 'tuck_end_phase_two_review_v1_draft',
    family: 'tuck_end_box',
    reviewScope: 'live_shadow',
    basicInfo: {
      conversationId: '2051',
      requestId: '7676',
      sampleReferenceId: null,
      rawText: '双插盒报价，7*5*5CM，350克白卡，正反四色，5000',
      motherPoolSources: ['phase_one_tuck_end_box', 'second_phase_tuck_end_box', 'tuck_end_related_structure_keyword'],
      phaseOne: {
        family: 'tuck_end_box',
        type: 'tuck_end_box',
        status: 'quoted',
      },
      secondPhase: {
        family: 'tuck_end_box',
        type: 'tuck_end_box',
        status: 'quoted',
        statusReasons: ['tuck_end_box_in_scope'],
      },
      variantTags: [],
    },
    bucketAssessment: {
      bucket: 'quoted_clean_subset',
      pathId: 'standard_double_tuck_main_item',
      inBucketReasons: ['标准双插主件路径', 'quoted 条件完整', 'family merge 与 packaging type 都稳定'],
      misbucketRisk: false,
      misbucketRiskReasons: [],
    },
    productAssessment: {
      familyMergeStable: true,
      packagingTypeStable: true,
      statusMatchesExpected: true,
      quotedMisrelease: false,
      highComplexityCorrectlyHandoff: null,
      quotedChecks: {
        packagingTypeResolved: true,
        coreMaterialRecipeComplete: true,
        keyLineItemsComputable: true,
        unresolvedTermsSafe: true,
      },
    },
    termAndCostAssessment: {
      blockingUnknownTerms: [],
      nonBlockingUnknownTerms: [],
      unknownCluster: false,
      unknownClusterTerms: [],
      manualAdjustmentPresent: false,
      manualAdjustmentTouchesCoreCost: false,
      coreManualAdjustmentLineCodes: [],
      lineItemsStable: true,
      stableLineItemCodes: ['face_paper', 'printing'],
      missingCoreLineItemCodes: ['die_mold', 'gluing'],
      priceProxySystematicDrift: null,
      priceProxyDriftDirection: 'not_enough_evidence',
      priceProxyNote: '第三条 clean quoted 样本，当前主要价值在于重复稳定性，不足以单独证明价格代理。',
    },
    conclusion: {
      disposition: 'limited_role_candidate',
      blockReason: null,
      reviewNote: '继续支持 standard_double_tuck_main_item 是当前唯一接近 limited role 的 live path。',
    },
  },
  {
    schemaVersion: 'tuck_end_phase_two_review_v1_draft',
    family: 'tuck_end_box',
    reviewScope: 'live_shadow',
    basicInfo: {
      conversationId: '2045',
      requestId: '7664',
      sampleReferenceId: null,
      rawText: '双插盒，7*5*5CM，350克白卡，正反四色，5000个',
      motherPoolSources: ['phase_one_tuck_end_box', 'second_phase_tuck_end_box', 'tuck_end_related_structure_keyword'],
      phaseOne: {
        family: 'tuck_end_box',
        type: 'tuck_end_box',
        status: 'quoted',
      },
      secondPhase: {
        family: 'tuck_end_box',
        type: 'tuck_end_box',
        status: 'quoted',
        statusReasons: ['tuck_end_box_in_scope'],
      },
      variantTags: [],
    },
    bucketAssessment: {
      bucket: 'quoted_clean_subset',
      pathId: 'standard_double_tuck_main_item',
      inBucketReasons: ['标准双插主件路径', 'shadow quoted 与 live quoted 对齐', '无 unknown term 与 manual adjustment'],
      misbucketRisk: false,
      misbucketRiskReasons: [],
    },
    productAssessment: {
      familyMergeStable: true,
      packagingTypeStable: true,
      statusMatchesExpected: true,
      quotedMisrelease: false,
      highComplexityCorrectlyHandoff: null,
      quotedChecks: {
        packagingTypeResolved: true,
        coreMaterialRecipeComplete: true,
        keyLineItemsComputable: true,
        unresolvedTermsSafe: true,
      },
    },
    termAndCostAssessment: {
      blockingUnknownTerms: [],
      nonBlockingUnknownTerms: [],
      unknownCluster: false,
      unknownClusterTerms: [],
      manualAdjustmentPresent: false,
      manualAdjustmentTouchesCoreCost: false,
      coreManualAdjustmentLineCodes: [],
      lineItemsStable: true,
      stableLineItemCodes: ['face_paper', 'printing'],
      missingCoreLineItemCodes: ['die_mold', 'gluing'],
      priceProxySystematicDrift: null,
      priceProxyDriftDirection: 'not_enough_evidence',
      priceProxyNote: '同一路径重复样本继续稳定，无 quoted 误放行迹象。',
    },
    conclusion: {
      disposition: 'limited_role_candidate',
      blockReason: null,
      reviewNote: 'quoted clean subset 目前最稳定的 live 表现集中在这条标准双插主件路径。',
    },
  },
  {
    schemaVersion: 'tuck_end_phase_two_review_v1_draft',
    family: 'tuck_end_box',
    reviewScope: 'live_shadow',
    basicInfo: {
      conversationId: '2074',
      requestId: '7758',
      sampleReferenceId: null,
      rawText: '双插盒配说明书，先看看结构化预报价',
      motherPoolSources: ['phase_one_tuck_end_box', 'tuck_end_related_structure_keyword'],
      phaseOne: {
        family: 'tuck_end_box',
        type: 'tuck_end_box',
        status: 'estimated',
      },
      secondPhase: {
        family: null,
        type: null,
        status: null,
        statusReasons: [],
      },
      variantTags: [],
    },
    bucketAssessment: {
      bucket: 'estimated_boundary',
      pathId: 'hanging_or_insert',
      inBucketReasons: ['主件是双插盒，但请求显式携带说明书 companion item', '不属于 quoted clean subset'],
      misbucketRisk: true,
      misbucketRiskReasons: ['当前 turn 没有产出 second-phase shadow payload，无法直接验证 family merge 与状态边界'],
    },
    productAssessment: {
      familyMergeStable: false,
      packagingTypeStable: false,
      statusMatchesExpected: false,
      quotedMisrelease: false,
      highComplexityCorrectlyHandoff: null,
      quotedChecks: {
        packagingTypeResolved: null,
        coreMaterialRecipeComplete: null,
        keyLineItemsComputable: null,
        unresolvedTermsSafe: null,
      },
    },
    termAndCostAssessment: {
      blockingUnknownTerms: [],
      nonBlockingUnknownTerms: [],
      unknownCluster: false,
      unknownClusterTerms: [],
      manualAdjustmentPresent: false,
      manualAdjustmentTouchesCoreCost: null,
      coreManualAdjustmentLineCodes: [],
      lineItemsStable: false,
      stableLineItemCodes: [],
      missingCoreLineItemCodes: ['manual_adjustment'],
      priceProxySystematicDrift: null,
      priceProxyDriftDirection: 'not_enough_evidence',
      priceProxyNote: '没有 second-phase shadow 输出，当前不能评价价格代理，只能先记为 live shadow coverage gap。',
    },
    conclusion: {
      disposition: 'blocked',
      blockReason: 'shadow_not_emitted_for_tuck_end_companion_path',
      reviewNote: '这是一条真实 estimated boundary 流量，但 second-phase 没有产出可复核 shadow，当前应先视为阻断。',
    },
  },
  {
    schemaVersion: 'tuck_end_phase_two_review_v1_draft',
    family: 'tuck_end_box',
    reviewScope: 'live_shadow',
    basicInfo: {
      conversationId: '2067',
      requestId: '7740',
      sampleReferenceId: null,
      rawText: '双插盒：7*5*5CM，350克白卡，正反四色，5000；内托：20*12CM，白卡 ，5000；说明书：20*5CM，80克双铜纸，双面四色印，折3折，5000；透明贴纸：2.4*3cm，透明贴纸，5000',
      motherPoolSources: ['phase_one_tuck_end_box', 'tuck_end_related_structure_keyword'],
      phaseOne: {
        family: 'tuck_end_box',
        type: 'tuck_end_box',
        status: 'estimated',
      },
      secondPhase: {
        family: 'folding_carton',
        type: 'folding_carton',
        status: 'estimated',
        statusReasons: ['flat_print_redirect', 'line_item_template_incomplete'],
      },
      variantTags: [],
    },
    bucketAssessment: {
      bucket: 'estimated_boundary',
      pathId: 'hanging_or_insert',
      inBucketReasons: ['双插主件外带内托、说明书、透明贴纸，属于 companion item 边界', '保持 estimated 是对的，但不应掉回 folding_carton'],
      misbucketRisk: true,
      misbucketRiskReasons: ['second-phase family merge 漂移到 folding_carton', 'bundle 路径缺少 tuck_end companion 语义承载'],
    },
    productAssessment: {
      familyMergeStable: false,
      packagingTypeStable: false,
      statusMatchesExpected: true,
      quotedMisrelease: false,
      highComplexityCorrectlyHandoff: null,
      quotedChecks: {
        packagingTypeResolved: false,
        coreMaterialRecipeComplete: true,
        keyLineItemsComputable: true,
        unresolvedTermsSafe: true,
      },
    },
    termAndCostAssessment: {
      blockingUnknownTerms: [],
      nonBlockingUnknownTerms: [],
      unknownCluster: false,
      unknownClusterTerms: [],
      manualAdjustmentPresent: false,
      manualAdjustmentTouchesCoreCost: false,
      coreManualAdjustmentLineCodes: [],
      lineItemsStable: false,
      stableLineItemCodes: ['face_paper', 'printing'],
      missingCoreLineItemCodes: ['manual_adjustment'],
      priceProxySystematicDrift: null,
      priceProxyDriftDirection: 'not_enough_evidence',
      priceProxyNote: '当前主要问题不是价格，而是 family merge 回落和 bundle 骨架缺项。',
    },
    conclusion: {
      disposition: 'blocked',
      blockReason: 'family_merge_drift_to_folding_carton',
      reviewNote: 'estimated 边界判断本身保守，但 family merge 不稳定，当前必须继续 shadow。',
    },
  },
  {
    schemaVersion: 'tuck_end_phase_two_review_v1_draft',
    family: 'tuck_end_box',
    reviewScope: 'live_shadow',
    basicInfo: {
      conversationId: '2066',
      requestId: '7736',
      sampleReferenceId: null,
      rawText: '说明书改成双面黑白',
      motherPoolSources: ['phase_one_tuck_end_box'],
      phaseOne: {
        family: 'tuck_end_box',
        type: 'tuck_end_box',
        status: 'estimated',
      },
      secondPhase: {
        family: 'folding_carton',
        type: 'folding_carton',
        status: 'estimated',
        statusReasons: ['flat_print_redirect', 'core_material_incomplete', 'line_item_template_incomplete'],
      },
      variantTags: [],
    },
    bucketAssessment: {
      bucket: 'estimated_boundary',
      pathId: 'hanging_or_insert',
      inBucketReasons: ['这是双插组合单里的 companion leaflet 变更', '应继续落在 estimated 边界'],
      misbucketRisk: true,
      misbucketRiskReasons: ['上下文仍是 tuck_end_box，但 second-phase 已回落到 folding_carton', 'follow-up turn 没有保住 tuck_end 主件语义'],
    },
    productAssessment: {
      familyMergeStable: false,
      packagingTypeStable: false,
      statusMatchesExpected: true,
      quotedMisrelease: false,
      highComplexityCorrectlyHandoff: null,
      quotedChecks: {
        packagingTypeResolved: false,
        coreMaterialRecipeComplete: false,
        keyLineItemsComputable: false,
        unresolvedTermsSafe: true,
      },
    },
    termAndCostAssessment: {
      blockingUnknownTerms: [],
      nonBlockingUnknownTerms: [],
      unknownCluster: false,
      unknownClusterTerms: [],
      manualAdjustmentPresent: false,
      manualAdjustmentTouchesCoreCost: false,
      coreManualAdjustmentLineCodes: [],
      lineItemsStable: false,
      stableLineItemCodes: [],
      missingCoreLineItemCodes: ['face_paper', 'printing', 'manual_adjustment'],
      priceProxySystematicDrift: null,
      priceProxyDriftDirection: 'not_enough_evidence',
      priceProxyNote: '这类 follow-up turn 当前更暴露 family merge 和 line-item coverage 缺口，而不是价格问题。',
    },
    conclusion: {
      disposition: 'blocked',
      blockReason: 'follow_up_turn_loses_tuck_end_identity',
      reviewNote: 'companion item follow-up 仍会让 second-phase 丢失 tuck_end 主件身份，当前不能前移角色。',
    },
  },
  {
    schemaVersion: 'tuck_end_phase_two_review_v1_draft',
    family: 'tuck_end_box',
    reviewScope: 'live_shadow',
    basicInfo: {
      conversationId: '2064',
      requestId: '7724',
      sampleReferenceId: null,
      rawText: '双插盒，7*5*5CM，5000个',
      motherPoolSources: ['phase_one_tuck_end_box', 'second_phase_tuck_end_box', 'tuck_end_related_structure_keyword'],
      phaseOne: {
        family: 'tuck_end_box',
        type: 'tuck_end_box',
        status: 'missing_fields',
      },
      secondPhase: {
        family: 'tuck_end_box',
        type: 'tuck_end_box',
        status: 'estimated',
        statusReasons: ['tuck_end_box_in_scope', 'core_material_incomplete', 'line_item_template_incomplete'],
      },
      variantTags: [],
    },
    bucketAssessment: {
      bucket: 'estimated_boundary',
      pathId: 'standard_double_tuck_main_item',
      inBucketReasons: ['仍是标准双插主件路径', '缺少材质、克重、印色，不能进入 quoted clean subset'],
      misbucketRisk: false,
      misbucketRiskReasons: [],
    },
    productAssessment: {
      familyMergeStable: true,
      packagingTypeStable: true,
      statusMatchesExpected: true,
      quotedMisrelease: false,
      highComplexityCorrectlyHandoff: null,
      quotedChecks: {
        packagingTypeResolved: true,
        coreMaterialRecipeComplete: false,
        keyLineItemsComputable: false,
        unresolvedTermsSafe: true,
      },
    },
    termAndCostAssessment: {
      blockingUnknownTerms: [],
      nonBlockingUnknownTerms: [],
      unknownCluster: false,
      unknownClusterTerms: [],
      manualAdjustmentPresent: false,
      manualAdjustmentTouchesCoreCost: false,
      coreManualAdjustmentLineCodes: [],
      lineItemsStable: false,
      stableLineItemCodes: [],
      missingCoreLineItemCodes: ['face_paper', 'printing', 'die_mold'],
      priceProxySystematicDrift: null,
      priceProxyDriftDirection: 'not_enough_evidence',
      priceProxyNote: '这是 clean path 的信息不完整样本，当前主要观察点是是否继续保持保守。',
    },
    conclusion: {
      disposition: 'keep_shadow',
      blockReason: null,
      reviewNote: '标准双插主件路径本身正确，但信息不完整，现阶段应继续 shadow 而不是推进角色。',
    },
  },
  {
    schemaVersion: 'tuck_end_phase_two_review_v1_draft',
    family: 'tuck_end_box',
    reviewScope: 'live_shadow',
    basicInfo: {
      conversationId: '2042',
      requestId: '7654',
      sampleReferenceId: null,
      rawText: '双插盒：7*5*5CM，350克白卡，正反四色，5000；内托：20*12CM，白卡 ，5000；说明书：20*5CM，80克双铜纸，双面四色印，折3折，5000；透明贴纸：2.4*3cm，透明贴纸，5000',
      motherPoolSources: ['phase_one_tuck_end_box', 'tuck_end_related_structure_keyword'],
      phaseOne: {
        family: 'tuck_end_box',
        type: 'tuck_end_box',
        status: 'estimated',
      },
      secondPhase: {
        family: 'folding_carton',
        type: 'folding_carton',
        status: 'estimated',
        statusReasons: ['flat_print_redirect', 'line_item_template_incomplete'],
      },
      variantTags: [],
    },
    bucketAssessment: {
      bucket: 'estimated_boundary',
      pathId: 'hanging_or_insert',
      inBucketReasons: ['主件 + companion items 的 bundle 组合路径', '预计应保守停在 estimated'],
      misbucketRisk: true,
      misbucketRiskReasons: ['second-phase 再次回落到 folding_carton，说明 family merge 漂移不是孤例'],
    },
    productAssessment: {
      familyMergeStable: false,
      packagingTypeStable: false,
      statusMatchesExpected: true,
      quotedMisrelease: false,
      highComplexityCorrectlyHandoff: null,
      quotedChecks: {
        packagingTypeResolved: false,
        coreMaterialRecipeComplete: true,
        keyLineItemsComputable: true,
        unresolvedTermsSafe: true,
      },
    },
    termAndCostAssessment: {
      blockingUnknownTerms: [],
      nonBlockingUnknownTerms: [],
      unknownCluster: false,
      unknownClusterTerms: [],
      manualAdjustmentPresent: false,
      manualAdjustmentTouchesCoreCost: false,
      coreManualAdjustmentLineCodes: [],
      lineItemsStable: false,
      stableLineItemCodes: ['face_paper', 'printing'],
      missingCoreLineItemCodes: ['manual_adjustment'],
      priceProxySystematicDrift: null,
      priceProxyDriftDirection: 'not_enough_evidence',
      priceProxyNote: '重复 bundle 样本继续复现 family merge 漂移，当前优先级仍是产品层稳定性，不是价格代理。',
    },
    conclusion: {
      disposition: 'blocked',
      blockReason: 'repeated_family_merge_drift_on_bundle_path',
      reviewNote: 'bundle estimated 路径当前稳定保守，但 family merge 不稳定，仍必须 shadow。',
    },
  },
  {
    schemaVersion: 'tuck_end_phase_two_review_v1_draft',
    family: 'tuck_end_box',
    reviewScope: 'live_shadow',
    basicInfo: {
      conversationId: '2041',
      requestId: '7650',
      sampleReferenceId: null,
      rawText: '说明书改成双面黑白',
      motherPoolSources: ['phase_one_tuck_end_box'],
      phaseOne: {
        family: 'tuck_end_box',
        type: 'tuck_end_box',
        status: 'estimated',
      },
      secondPhase: {
        family: 'folding_carton',
        type: 'folding_carton',
        status: 'estimated',
        statusReasons: ['flat_print_redirect', 'core_material_incomplete', 'line_item_template_incomplete'],
      },
      variantTags: [],
    },
    bucketAssessment: {
      bucket: 'estimated_boundary',
      pathId: 'hanging_or_insert',
      inBucketReasons: ['双插组合单里的 companion leaflet follow-up', '应继续是 estimated boundary'],
      misbucketRisk: true,
      misbucketRiskReasons: ['second-phase 对 follow-up turn 仍无法保住 tuck_end 主路径'],
    },
    productAssessment: {
      familyMergeStable: false,
      packagingTypeStable: false,
      statusMatchesExpected: true,
      quotedMisrelease: false,
      highComplexityCorrectlyHandoff: null,
      quotedChecks: {
        packagingTypeResolved: false,
        coreMaterialRecipeComplete: false,
        keyLineItemsComputable: false,
        unresolvedTermsSafe: true,
      },
    },
    termAndCostAssessment: {
      blockingUnknownTerms: [],
      nonBlockingUnknownTerms: [],
      unknownCluster: false,
      unknownClusterTerms: [],
      manualAdjustmentPresent: false,
      manualAdjustmentTouchesCoreCost: false,
      coreManualAdjustmentLineCodes: [],
      lineItemsStable: false,
      stableLineItemCodes: [],
      missingCoreLineItemCodes: ['face_paper', 'printing', 'manual_adjustment'],
      priceProxySystematicDrift: null,
      priceProxyDriftDirection: 'not_enough_evidence',
      priceProxyNote: '当前是 follow-up 语义保持问题，不是价格代理问题。',
    },
    conclusion: {
      disposition: 'blocked',
      blockReason: 'follow_up_turn_family_merge_drift',
      reviewNote: 'follow-up 说明书变更会让 second-phase 失去 tuck_end 归并，必须继续 shadow。',
    },
  },
] as const satisfies readonly TuckEndPhaseTwoManualReviewDraft[]

export const TUCK_END_PHASE_TWO_LIVE_REVIEW_BATCH_ONE_SUMMARY_DRAFT = {
  batchId: 'tuck_end_phase_two_live_review_batch_one_2026_04_05',
  family: 'tuck_end_box',
  reviewedCount: 10,
  bucketCounts: {
    quoted_clean_subset: 4,
    estimated_boundary: 6,
    handoff_boundary: 0,
  },
  dispositionCounts: {
    keep_shadow: 1,
    limited_role_candidate: 4,
    blocked: 5,
  },
  wrongBucketCount: 5,
  quotedMisreleaseCount: 0,
  handoffBoundarySampleCount: 0,
  handoffBoundaryCoverageGap: true,
  currentClosestLimitedRoleCandidatePath: 'standard_double_tuck_main_item',
  pathsThatMustRemainShadow: [
    'hanging_or_insert companion path',
    'bundle follow-up path that drifts to folding_carton',
    'standard double-tuck path with incomplete core material',
    'all handoff-boundary paths until real live traffic appears',
  ],
  keyFindings: [
    '标准双插主件 quoted clean subset 在首批 live review 中连续 4 条保持 family/type/status 全对齐。',
    '当前没有发现 second-phase 把应 estimated 的样本误放行为 quoted。',
    'estimated bundle/companion 路径重复出现 family merge 从 tuck_end_box 漂移到 folding_carton。',
    '真实流量里暂未观察到 tuck_end handoff-boundary 样本，handoff 仍处于 coverage gap 状态。',
  ],
} as const